from __future__ import annotations

import json
import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SCAFFOLD = ROOT / "skills/scaffold-research-task/scripts/scaffold_research_task.py"
VALIDATE = ROOT / "skills/scaffold-research-task/scripts/validate_research_scaffold.py"


def run(script: Path, *arguments: object) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(script), *(str(argument) for argument in arguments)],
        cwd=ROOT,
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )


def create_scaffold(target: Path, profile: str = "literature-review") -> None:
    result = run(
        SCAFFOLD,
        "--target",
        target,
        "--task-name",
        "Validation study",
        "--profile",
        profile,
        "--apply",
    )
    assert result.returncode == 0, result.stderr


def validate(target: Path) -> subprocess.CompletedProcess[str]:
    return run(VALIDATE, "--target", target)


def test_valid_and_extra_files_are_allowed(root: Path) -> None:
    target = root / "valid"
    create_scaffold(target, "existing-repository")
    result = validate(target)
    assert result.returncode == 0, result.stderr
    assert "governance-connect" in result.stdout
    assert not (target / "AGENTS.md").exists()

    (target / "USER_NOTES.md").write_text("user material\n", encoding="utf-8")
    result = validate(target)
    assert result.returncode == 0, result.stderr


def test_missing_required_file_fails(root: Path) -> None:
    target = root / "missing"
    create_scaffold(target)
    (target / "reports/README.md").unlink()
    result = validate(target)
    assert result.returncode == 1
    assert "missing required file: reports/README.md" in result.stderr


def test_manifest_generator_tamper_fails(root: Path) -> None:
    target = root / "generator"
    create_scaffold(target)
    path = target / "RESEARCH_TASK_PROFILE.json"
    payload = json.loads(path.read_text(encoding="utf-8"))
    payload["generated_by"]["version"] = "9.9.9"
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    result = validate(target)
    assert result.returncode == 1
    assert "generator identity" in result.stderr


def test_manifest_module_contract_fails(root: Path) -> None:
    target = root / "modules"
    create_scaffold(target, "local-ml")
    path = target / "RESEARCH_TASK_PROFILE.json"
    payload = json.loads(path.read_text(encoding="utf-8"))
    payload["modules"] = ["base"]
    payload["package_name"] = None
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    result = validate(target)
    assert result.returncode == 1
    assert "do not satisfy the named profile" in result.stderr


def test_unresolved_template_token_fails(root: Path) -> None:
    target = root / "token"
    create_scaffold(target)
    path = target / "evidence/README.md"
    original = path.read_text(encoding="utf-8")
    for token in ("{{missing}}", "{{task_name}}"):
        path.write_text(original + token + "\n", encoding="utf-8")
        result = validate(target)
        assert result.returncode == 1
        assert "unresolved template token" in result.stderr


def test_nested_json_and_literal_braces_are_allowed(root: Path) -> None:
    target = root / "json_example"
    create_scaffold(target, "local-ml")
    path = target / "configs/README.md"
    example = json.dumps({"analysis": {"seed": 7}})
    path.write_text(
        path.read_text(encoding="utf-8")
        + f"\n```json\n{example}\n```\nLiteral brace pairs: `{{{{` and `}}}}`.\n",
        encoding="utf-8",
    )
    result = validate(target)
    assert result.returncode == 0, result.stderr


def test_legacy_layout_retains_its_generator_identity(
    root: Path, legacy_version: str
) -> None:
    target = root / f"legacy_{legacy_version}"
    create_scaffold(target, "third-party-remote")
    path = target / "RESEARCH_TASK_PROFILE.json"
    payload = json.loads(path.read_text(encoding="utf-8"))
    current_version = payload["generated_by"]["version"]
    payload["generated_by"]["version"] = legacy_version
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    current_marker = f"Generated by scaffold-research-task v{current_version}"
    legacy_marker = f"Generated by scaffold-research-task v{legacy_version}"
    for document in target.rglob("*.md"):
        document.write_text(
            document.read_text(encoding="utf-8").replace(current_marker, legacy_marker),
            encoding="utf-8",
        )
    # Legacy documents need not adopt new orientation guidance to remain valid.
    for relative in ("RESEARCH_ARCHITECTURE.md", "configs/README.md"):
        (target / relative).write_text(
            f"# Existing research notes\n\n{legacy_marker}.\n\n"
            "User-owned design notes retained without new sections.\n",
            encoding="utf-8",
        )
    before = {item: item.read_bytes() for item in target.rglob("*") if item.is_file()}
    result = validate(target)
    assert result.returncode == 0, result.stderr
    assert before == {item: item.read_bytes() for item in before}

    document = target / "RESEARCH_TASK.md"
    document.write_text(
        document.read_text(encoding="utf-8").replace(legacy_marker, current_marker),
        encoding="utf-8",
    )
    result = validate(target)
    assert result.returncode == 1
    assert "missing generator marker" in result.stderr


def test_missing_marker_fails(root: Path) -> None:
    target = root / "marker"
    create_scaffold(target)
    path = target / "RESEARCH_TASK.md"
    text = path.read_text(encoding="utf-8").replace(
        "Generated by scaffold-research-task v0.1.2.\n", ""
    )
    path.write_text(text, encoding="utf-8")
    result = validate(target)
    assert result.returncode == 1
    assert "missing generator marker" in result.stderr


def main() -> int:
    with tempfile.TemporaryDirectory(prefix="validate-research-scaffold-") as directory:
        root = Path(directory)
        test_valid_and_extra_files_are_allowed(root)
        test_missing_required_file_fails(root)
        test_manifest_generator_tamper_fails(root)
        test_manifest_module_contract_fails(root)
        test_unresolved_template_token_fails(root)
        test_nested_json_and_literal_braces_are_allowed(root)
        for legacy_version in ("0.1.0", "0.1.1"):
            test_legacy_layout_retains_its_generator_identity(root, legacy_version)
        test_missing_marker_fails(root)
    print("PASS: scaffold validation behavior checks passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
