from __future__ import annotations

import json
import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SCAFFOLD = ROOT / "skills/scaffold-research-task/scripts/scaffold_research_task.py"
VALIDATE = ROOT / "skills/scaffold-research-task/scripts/validate_research_scaffold.py"


def run(script: Path, *arguments: object) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(script), *(str(argument) for argument in arguments)],
        cwd=ROOT,
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )


def create_scaffold(target: Path, profile: str = "literature-review") -> None:
    result = run(
        SCAFFOLD,
        "--target",
        target,
        "--task-name",
        "Validation study",
        "--profile",
        profile,
        "--apply",
    )
    assert result.returncode == 0, result.stderr


def validate(target: Path) -> subprocess.CompletedProcess[str]:
    return run(VALIDATE, "--target", target)


def test_valid_and_extra_files_are_allowed(root: Path) -> None:
    target = root / "valid"
    create_scaffold(target, "existing-repository")
    result = validate(target)
    assert result.returncode == 0, result.stderr
    assert "governance-connect" in result.stdout
    assert not (target / "AGENTS.md").exists()

    (target / "USER_NOTES.md").write_text("user material\n", encoding="utf-8")
    result = validate(target)
    assert result.returncode == 0, result.stderr


def test_missing_required_file_fails(root: Path) -> None:
    target = root / "missing"
    create_scaffold(target)
    (target / "reports/README.md").unlink()
    result = validate(target)
    assert result.returncode == 1
    assert "missing required file: reports/README.md" in result.stderr


def test_manifest_generator_tamper_fails(root: Path) -> None:
    target = root / "generator"
    create_scaffold(target)
    path = target / "RESEARCH_TASK_PROFILE.json"
    payload = json.loads(path.read_text(encoding="utf-8"))
    payload["generated_by"]["version"] = "9.9.9"
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    result = validate(target)
    assert result.returncode == 1
    assert "generator identity" in result.stderr


def test_manifest_module_contract_fails(root: Path) -> None:
    target = root / "modules"
    create_scaffold(target, "local-ml")
    path = target / "RESEARCH_TASK_PROFILE.json"
    payload = json.loads(path.read_text(encoding="utf-8"))
    payload["modules"] = ["base"]
    payload["package_name"] = None
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    result = validate(target)
    assert result.returncode == 1
    assert "do not satisfy the named profile" in result.stderr


def test_unresolved_template_token_fails(root: Path) -> None:
    target = root / "token"
    create_scaffold(target)
    path = target / "evidence/README.md"
    path.write_text(path.read_text(encoding="utf-8") + "{{missing}}\n", encoding="utf-8")
    result = validate(target)
    assert result.returncode == 1
    assert "unresolved template token" in result.stderr


def test_missing_marker_fails(root: Path) -> None:
    target = root / "marker"
    create_scaffold(target)
    path = target / "RESEARCH_TASK.md"
    text = path.read_text(encoding="utf-8").replace(
        "Generated by scaffold-research-task v0.1.0.\n", ""
    )
    path.write_text(text, encoding="utf-8")
    result = validate(target)
    assert result.returncode == 1
    assert "missing generator marker" in result.stderr


def main() -> int:
    with tempfile.TemporaryDirectory(prefix="validate-research-scaffold-") as directory:
        root = Path(directory)
        test_valid_and_extra_files_are_allowed(root)
        test_missing_required_file_fails(root)
        test_manifest_generator_tamper_fails(root)
        test_manifest_module_contract_fails(root)
        test_unresolved_template_token_fails(root)
        test_missing_marker_fails(root)
    print("PASS: scaffold validation behavior checks passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
